name: Release latest ifupdown2 version

on:
  push:

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set TAG name
        run: |
          echo "TAG_NAME=ifupdown2-$(date +"%Y.%m.%d")" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          sudo apt install build-essential devscripts dh-python python3-all python3-docutils debhelper

      - name: Make deb-package
        run: |
          git checkout master
          sudo make deb

      - name: Upload to Releases
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          tag_name: ${{ env.TAG_NAME }}
          body: ${{ env.TAG_NAME }}
          files: ../ifupdown2_3.2.0_all.deb
